### ISSUE TITLE
~nus and ~marnus not responding

### ISSUE THREAD

**Issue by crrncllns** [urbit/support#10]
~loddyl-wanned can't connect

**Comment by vvisigoth** [comment]
~marnus is having surgery performed on it right now, should be back up later today.

**Comment by vvisigoth** [comment]
check twitter.com/zodisok

**Comment by oggonz** [comment]
Hi, any updates?

**Comment by vvisigoth** [comment]
These have both been brought back up, can you reach them now?

**Comment by oggonz** [comment]
Let me check tonight. Thanks for taking the time.

**Comment by oggonz** [comment]
Thanks folks. I managed to reach `nus is ok` though marnus is still unreachable. I'm now also receiving ancillary networking errors which I suspect may be due to managing key files incorrectly, so I'm going to try to reset my keys and breach, to see if that solves it. 

Update: some bonking, and re-connecting to ~marnus ~nus etc later, I'm good to go! Thanks a bunch guys. See everybody online.

**Comment by vvisigoth** [comment]
great!
